import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ThemeProvider } from "@/components/Theme-provider";
import QueryClientProvider from "@/app/_components/QueryClientProvider";
import { cn } from "@/lib/utils";

import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import SessionProvider from "@/components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const clientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
    return (
        <html lang='en'>
            <GoogleOAuthProvider clientId={clientId as string}>
                <QueryClientProvider>
                    <SessionProvider>
                        <body
                            className={cn(
                                "min-h-screen bg-background font-sans antialiased",
                                inter.className
                            )}>
                            <ThemeProvider
                                attribute='class'
                                defaultTheme='system'
                                enableSystem
                                disableTransitionOnChange
                                storageKey='pentakill-theme'>
                                {children}
                            </ThemeProvider>
                            <ReactQueryDevtools />
                        </body>
                    </SessionProvider>
                </QueryClientProvider>
            </GoogleOAuthProvider>
        </html>
    );
}
